config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :softwares
  resources :printers
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}
  resources :users, :only => [:show]

  get 'password_resets/new'

  get 'password_resets/edit'

  root      'static_pages#home'
  get       '/help',    to: 'static_pages#help'
  get       '/about',   to: 'static_pages#about'
  get       '/contact', to: 'static_pages#contact'
  get       '/search', to: 'search#index'
	
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup


  
  resources :users do 
    resources :creations, shallow: true
    resources :friendships
  end


  resources :comments

  resources :creations, shallow: true do 
    get :download
    get :fork
  end

  resources :user_files, only: [:destroy, :create]

  resources :categories

  resources :likes, only: [:create,:destroy]
  
  resources :follows, only: [:create,:destroy]

  resources :account_activations, only: [:edit]


  resources :challenges

  resources :conversations, shallow: true do
    resources :messages
  end
  
  mount ActionCable.server, at: '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController  
  before_action :authenticate_user!

  def create
    commentable = commentable_type.constantize.find(commentable_id)
    @comment = Comment.build_from(commentable, current_user.id, body)

    respond_to do |format|
      if @comment.save
        make_child_comment
        format.html  { redirect_to(:back, :notice => 'Comment was successfully added.') }
      else
        format.html  { render :action => "new" }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type, :comment_id)
  end

  def commentable_type
    comment_params[:commentable_type]
  end

  def commentable_id
    comment_params[:commentable_id]
  end

  def comment_id
    comment_params[:comment_id]
  end

  def body
    comment_params[:body]
  end

  def make_child_comment
    return "" if comment_id.blank?

    parent_comment = Comment.find comment_id
    @comment.move_to_child_of(parent_comment)
  end

end  

app/helpers/comments_helper.rb
module CommentsHelper
	def nested_comments(comments, isnested = false)
  	comments.map do |comment, sub_comment|
    		render(comment) + nested_comments(sub_comment)
  	end.join.html_safe
	end
end

app/views/comments/_comment.html.erb
<article class="row <%= "root_comment_" + comment.root.id.to_s  %> comment_block" >
	<% if comment.depth > 0 %> 
	  <div class="col-md-2 col-sm-2 col-md-offset-1 col-sm-offset-0 hidden-xs ">
	<% else %>
		  <div class="col-md-2 col-sm-2 hidden-xs"> 
	<% end %> 
    <figure class="thumbnail">
      <img class="img-responsive" src="http://www.keita-gaming.com/assets/profile/default-avatar-c5d8ec086224cb6fc4e395f4ba3018c2.jpg" />
      <figcaption class="text-center"><%= comment.user.name %></figcaption>
    </figure>
  </div>
  <% if comment.depth > 0 %> 
 		<div class="col-md-9 col-sm-9">
	<% else %>
 		<div class="col-md-10 col-sm-10">
	<% end %> 
    <div class="panel panel-default arrow left">
      <div class="panel-body">
        <header class="text-left">
          <div class="comment-user"><i class="fa fa-user"></i><%= comment.user.name %></div>
          <time class="comment-date'" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> <%= comment.created_at %></time>
        </header>
        <div class="comment-post">
          <p>
            <%= comment.body %>
          </p>
        </div>

        <% if user_signed_in?  && (current_user.admin? || current_user.id == comment.user_id) %> 
          <p class="text-right"><%= link_to_if current_user.admin? || current_user.id == comment.user_id, "Edit", edit_comment_path(comment), :class => "edit-comment", remote: true %></p>
          <p class="text-right"><%= link_to_if current_user.admin? || current_user.id == comment.user_id, "Delete", comment_path(comment), method: :delete, :class => "delete-comment", remote: true %></p>
        <% end %>
        <%if user_signed_in? %>
          <p class="text-right"><%= link_to "Reply", new_polymorphic_path([@commentable, Comment.new], :parent_id => comment), :class => "reply-to-comment", remote: true %></p>
        <% end %>
      </div>
    </div>
  </div>
</article>

app/views/comments/_comments.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h2 class="page-header">Comments</h2>
        <section class="comment-list">
					<%= nested_comments @comments %>
					<%= render "comments/form" if user_signed_in? %>
        </section>
    </div>
  </div>
</div>

app/views/comments/_edit.html.erb
<article class="row">
	<%= form_for [@comment], :remote=>true do |f| %>

		<%= f.hidden_field :commentable_id %>
		<%= f.hidden_field :commentable_type %> 

	<% if @comment.parent_id %> 
		<div class="col-md-2 col-sm-2 col-md-offset-1 col-sm-offset-0  update-comment hidden-xs">
  <% else %>
  	<div class="col-md-2 col-sm-2  update-comment hidden-xs">
  <% end %> 
    <figure class="thumbnail">
      <img class="img-responsive" src="http://www.keita-gaming.com/assets/profile/default-avatar-c5d8ec086224cb6fc4e395f4ba3018c2.jpg" />
      <figcaption class="text-center"><%= @comment.user.name %></figcaption>
    </figure>
  </div>
	<% if @comment.parent_id %> 
  	<div class="col-md-9 col-sm-9">		
  <% else %> 
  	<div class="col-md-10 col-sm-10">
  <% end %> 
    <div class="panel panel-default arrow left">
      <div class="panel-body">
        <header class="text-left">
          <div class="comment-user"><i class="fa fa-user"></i><%= @comment.user.name %></div>
          <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> <%= @comment.created_at %></time>
        </header>
        <div class="comment-post">
					<%= f.label :body, "Update Comment" %>
					<%= f.text_area :body, :rows => 4 %>
        </div>
        	<%= f.submit "Save Changes" %>
      </div>
    </div>
  </div>
</article>

<% end %>

app/views/comments/_form.html.erb
<%= form_for @new_comment do |f| %>  
  <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
  <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
  <div class="field form-group">
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= submit_tag "Post comment", class: 'btn btn-primary' %>
  </div>
<% end %>  

app/views/comments/_reply.html.erb
<% comments.each do |comment| %>  
  <div class="comments-show">
    <div class="comment">
      <%= comment.user.name %> 
      <p><%= comment.body %><br></p>
      <div class="comment-nav"><a href="#" class="comment-reply">reply</a></div>
      <div class="reply-form">
        <%= form_for @new_comment do |f| %>
          <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
          <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
          <%= f.hidden_field :comment_id, value: comment.id %>
          <div class="field form-group">
            <%= f.text_area :body, class: 'form-control' %>
          </div>
          <div class="field form-group">
            <%= submit_tag "Post Reply", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
    <%= render partial: "comments/reply", locals: {comments: comment.children} %>
  </div>
<% end %>  

app/views/comments/_template.html.erb
<div class="comments-header">  
  <h4>
    <%= commentable.comment_threads.count == 0 ? "no" : commentable.comment_threads.count %> comments
  </h4>
</div>

<%= render partial: "comments/form", locals: {new_comment: new_comment} %>

<div class="comments-container">  
  <%= render partial: "comments/reply", locals: {comments: commentable.root_comments} %>
</div>  

app/views/comments/new.html.erb
<%= render 'form' %>