config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :softwares
  resources :printers
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}
  resources :users, :only => [:show]

  get 'password_resets/new'

  get 'password_resets/edit'

  root      'static_pages#home'
  get       '/help',    to: 'static_pages#help'
  get       '/about',   to: 'static_pages#about'
  get       '/contact', to: 'static_pages#contact'
  get       '/search', to: 'search#index'
	
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup


  
  resources :users do 
    resources :creations, shallow: true
    resources :friendships
  end


  resources :comments

  resources :creations, shallow: true do 
    get :download
    get :fork
  end

  resources :user_files, only: [:destroy, :create]

  resources :categories

  resources :likes, only: [:create,:destroy]
  
  resources :follows, only: [:create,:destroy]

  resources :account_activations, only: [:edit]


  resources :challenges

  resources :conversations, shallow: true do
    resources :messages
  end
  
  mount ActionCable.server, at: '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  ratyrate_rater

  after_save ThinkingSphinx::RealTime.callback_for(:user)


  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :omniauthable,
         :confirmable, :validatable
         

  has_many :authentications, :dependent => :destroy
  has_many :creations, dependent: :destroy
  has_many :comments
  has_many :impressions, :as=>:impressionable, dependent: :destroy


  has_many :friendships, :dependent => :destroy
  has_many :friends, -> { where(friendships: {status: "accepted"} ) }, :through => :friendships
  has_many :requested_friends, -> { where(friendships: {status: "requested"} ).order(created_at: :desc) },  :through => :friendships, :source => :friend
  has_many :pending_friends,  -> { where(friendships: {status: "pending"} ).order(created_at: :desc) },  :through => :friendships, :source => :friend
  
  has_many :likes
  has_many :creations_liked, through: :likes, source: :liked, source_type: 'Creation'
  
  has_many :follows
  has_many :users_following, through: :follows, source: :followed, source_type: "User"
  has_many :creations_following, through: :follows, source: :followed, source_type: "Creation"

  has_many :user_conversations
  has_many :conversations, :through => :user_conversations
  has_many :messages, :through => :conversations


  mount_uploader :avatar, FileUploader
  mount_uploader :banner, FileUploader


  validates :name, presence: true, length: { maximum: 50}







  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    authentication = Authentication.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : authentication.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the authentication with the user if needed
    if authentication.user != user
      authentication.user = user
      authentication.save!
    end
    user
  end


  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :log_impression, :only => [:show]

  def show
    @user = User.find(params[:id])
    @creations = @user.creations.paginate(:page => params[:creations_page])
    @liked = @user.creations_liked.paginate(:page => params[:liked_page]);
    @following = @user.creations_following.paginate(:page => params[:following_page]);
  end

   # GET /users/:id/edit
  def edit
   # authorize! :update, @user
  end

	def index
		@users= User.all.paginate(:page => params[:page])
	end

 # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user 
    if request.patch? && params[:user] && params[:user][:email]
      current_user.skip_reconfirmation!
      if current_user.update(user_params)
        sign_in(current_user, :bypass => true)
        redirect_to current_user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  
  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email, :avatar, :banner ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      accessible << [:website, :location, :bio]
      params.require(:user).permit(accessible)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<div class="col-xs-4">
    <div href="#" class="thumbnail">
	      <%= link_to user do %>
	        <img src="<%= user.avatar.url %>" alt="..." />
      <div class="caption">

					<%= user.name %>
					<% if  current_user && current_user.admin? && current_user != user %>
						| <%= link_to "delete", user, method: :delete,
		                          data: { confirm: "You sure?" } %>
					<% end %>  
				<% end %>
    	</div>
    </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :bio %>
      <%= f.text_area :bio, class: 'form-control' %>

      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>

      <%= f.label :website %>
      <%= f.url_field :website, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :avatar %>
      <%= f.file_field :avatar %>

      <%= f.label :banner %>
      <%= f.file_field :banner %>


      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/finish_signup.html.erb
<div id="add-email" class="container">
  <h1>Add Email</h1>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
    <% if @show_errors && current_user.errors.any? %>
      <div id="error_explanation">
        <% current_user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :email %>
      <div class="controls">
        <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
        <p class="help-block">Please confirm your email address. No spam.</p>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Continue', :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>


<div class="container">
	<div class="row">
		<%= render @users %>
	</div>
</div>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <div class="row profile-page-row">
    <aside class="col-md-3">
      <section class="user_info">
        <div>
          <img src="<%= @user.avatar.url(:thumb) %>" id="profile-pic" class="img-circle">
          <h4>
            <%= @user.name %>
          </h4>
        </div>
        <hr>

        <div class="user-details">
          <p><span class="glyphicon glyphicon-envelope"></span> <%= @user.email %></p>
          <p><span class="glyphicon glyphicon-link"></span><a href="<%= @user.website %>"> <%= @user.website %></a></p>
        </div>
        <hr>

        <div class="actions">
          <h4>Actions</h4>
          <% if current_user == @user %>
          <%= link_to "New Creation", new_user_creation_url(@user) %> </br>
          <%= link_to("Settings", edit_user_path(current_user)) %>
          <% end %>  
          <% if user_signed_in? && current_user != @user  %>
          <% if current_user.friends.include? @user %>
          <span class="label label-primary">Friends</span>
          <% elsif current_user.requested_friends.include? @user %>
          <%= render partial: 'friendships/requested' %>
          <% elsif current_user.pending_friends.include? @user %>
          <%= render partial: 'friendships/pending' %>
          <% else %>
          <%= render partial: 'friendships/form' %>
          <% end %>
          <% end %>
        </div>

        <hr>

      </section>
    </aside>

    <div class="col-md-9 tab-content">
      <%= image_tag @user.banner, :id => "banner-pic"%>
      <ul class="nav nav-tabs nav-justified">
       <li class="<%= "#{'active' unless params[:active_tab] == 'creations'} "%>"><a data-toggle="pill" href="#creations">Creations</a></li>       
        <!-- <li class=""><a data-toggle="pill" href="#printed">Printed Creations</a></li> -->
        <!-- <li class=""><a data-toggle="pill" href="#followers">Followers</a></li> -->
        <li class=""><a data-toggle="pill" href="#following">Following</a></li>
        <li class=""><a data-toggle="pill" href="#liked">Liked</a></li>
        <li class="<%= "#{'active' if params[:active_tab] == 'creations'} "%>"><a data-toggle="pill" href="#about">About</a></li>
      </ul>







      <div id="creations" class="tab-pane <%= "#{'fade in active' unless params[:active_tab] == 'creations'} "%>">
        <% if @user.creations.any? %>
        <h3>Creations (<%= @user.creations.count %>)</h3>
        <div class="pagination-bar"> 
          <%= will_paginate @creations, :param_name => 'creations_page', params: {active_tab: 'creations'}  %>
        </div>
        <div class="clearfix">
          <%= render @creations %>
        </div>
        <div class="pagination-bar">
          <%= will_paginate @creations, :param_name => 'creation_page', params: {active_tab: 'creations'}   %>
        </div>
        <% end %>
      </div>



      <!-- <div id="made" class="tab-pane fade"> -->
      <!-- </div> -->

      <!-- <div id="followers" class="tab-pane fade"> -->
      <!-- </div> -->

      <div id="following" class="tab-pane fade">
        <div class="pagination-bar"> 
          <%= will_paginate @following, :param_name => 'following_page', params: {active_tab: 'following'}  %>
        </div>
        <div class="clearfix">
          <%= render @following %>
        </div>
        <div class="pagination-bar">
          <%= will_paginate @following, :param_name => 'following_page', params: {active_tab: 'following'}   %>
        </div>
      </div>

      <div id="liked" class="tab-pane fade">
        <div class="pagination-bar"> 
          <%= will_paginate @liked, :param_name => 'liked_page', params: {active_tab: 'liked'}  %>
        </div>
        <div class="clearfix">
          <%= render @liked %>
        </div>
        <div class="pagination-bar">
          <%= will_paginate @liked, :param_name => 'liked_page', params: {active_tab: 'liked'}   %>
        </div>
      </div>

      <div id="about" class="tab-pane fade">
        <h4>Stats</h4>

        <div class="row">

          <div class="col-xs-6 col-md-3">
            <div class="stat">
              <div class="stat-detail">
                <p class="card-text">Views</p>
                <h4 class="card-title"><%= @user.impressions.count %></h4>
              </div>
            </div>
          </div>
          <div class="col-xs-6 col-md-3">

            <div class="stat">
              <div class="stat-detail">
                <p class="card-text">Creations</p>
                <h4 class="card-title"><%= @user.creations.count %></h4>
              </div>
            </div>   
          </div>
          <div class="col-xs-6 col-md-3">

            <div class="stat">
              <div class="stat-detail">
                <p class="card-text">Likes</p>
                <h4 class="card-title"><%= @user.likes.count %></h4>
              </div>
            </div>
          </div>
          <div class="col-xs-6 col-md-3">

            <div class="stat">
              <div class="stat-detail">
                <p class="card-text">Friends</p>
                <h4 class="card-title"><%= @user.friends.count %></h4>
              </div>
            </div>                    
          </div>       
        </div>   

        <hr>
        <h2>Why I'm Awesome</h2>
        <p><%= @user.bio %></p>
      </div>

    </div>
  </div>
</div>