config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :softwares
  resources :printers
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}
  resources :users, :only => [:show]

  get 'password_resets/new'

  get 'password_resets/edit'

  root      'static_pages#home'
  get       '/help',    to: 'static_pages#help'
  get       '/about',   to: 'static_pages#about'
  get       '/contact', to: 'static_pages#contact'
  get       '/search', to: 'search#index'
	
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup


  
  resources :users do 
    resources :creations, shallow: true
    resources :friendships
  end


  resources :comments

  resources :creations, shallow: true do 
    get :download
    get :fork
  end

  resources :user_files, only: [:destroy, :create]

  resources :categories

  resources :likes, only: [:create,:destroy]
  
  resources :follows, only: [:create,:destroy]

  resources :account_activations, only: [:edit]


  resources :challenges

  resources :conversations, shallow: true do
    resources :messages
  end
  
  mount ActionCable.server, at: '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, :class_name => 'User', :foreign_key =>'friend_id'  
	validates :user_id, :uniqueness => {:scope => :friend_id}
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	before_action :logged_in_user, :except => [:index, :show]

	def index
		@user = User.find(params[:user_id])
	end
	
	def show
		redirect_to user_path(params[:id])
	end
	
	def new
		@friendship1 = Friendship.new
		@friendship2 = Friendship.new
	end

	def create
		@user = User.find(current_user)
		@friend = User.find(params[:user_id])

		params[:friendship1] = {:user_id => @user.id, :friend_id => params[:user_id], :status => 'requested'}
		params[:friendship2] = {:user_id => @friend.id, :friend_id => @user.id, :status => 'pending'}
		
		@friendship1 = Friendship.create(friendships1_params)
		@friendship2 = Friendship.create(friendships2_params)

		respond_to do |format|
			if @friendship1.save && @friendship2.save
				flash.now[:success] = 'Friend Request Has Been Sent'
				commentPartial = (render partial: 'shared/error_messages')
				format.js { commentPartial.to_json }
			else
				flash.now[:danger] = @friendship1.errors.full_messages.to_sentence
    		format.js { render partial: 'shared/error_messages' ,status: :unprocessable_entity }
			end 
		end
	end

	def update

		@user = User.find(current_user)
		@friend = User.find(params[:id])
		params[:friendship1] = {:user_id => @user.id, :friend_id => @friend.id, :status => 'accepted'}
		params[:friendship2] = {:user_id => @friend.id, :friend_id => @user.id, :status => 'accepted'}
		@friendship1 = Friendship.find_by_user_id_and_friend_id(@user.id, @friend.id)
		@friendship2 = Friendship.find_by_user_id_and_friend_id(@friend.id, @user.id)
		
		respond_to do |format|

		if @friendship1.update_attributes(friendships1_params) && @friendship2.update_attributes(friendships2_params)
		
				flash[:notice] = 'Friend sucessfully accepted!'
				commentPartial = (render partial: 'shared/error_messages')
				format.js { commentPartial.to_json }
			
			else
				flash.now[:danger] = @friendship1.errors.full_messages.to_sentence
    		format.js { render partial: 'shared/error_messages' ,status: :unprocessable_entity }
			
			end 
		end




	end

	def destroy
		@user = User.find(params[:user_id])
		@friend = User.find(params[:id])
		@friendship1 = @user.friendships.find_by_friend_id(params[:id]).destroy
		@friendship2 = @friend.friendships.find_by_user_id(params[:id]).destroy
		redirect_to user_friends_path(:user_id => current_user)
	end


	private

	  def friendships1_params
      params.require(:friendship1).permit(:user_id, :friend_id, :status)
    end
	  def friendships2_params
      params.require(:friendship2).permit(:user_id, :friend_id, :status)
    end

end

app/views/friendships/_form.html.erb
<%= form_for [@user, Friendship.new], remote: true do  |f| %>
	<%= f.submit "Request Friend", class: 'btn btn-default'%>
<% end %>

app/views/friendships/_friend.html.erb
<% if defined? friend %>
	<div class="col-xs-4">
	    <div href="#" class="thumbnail">
	      <img src="http://placehold.it/400x200" alt="..." />
	      <div class="caption">
		      <%= link_to friend.name, friend %>
					<div class="dropdown">
					  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Friend
					  <span class="caret"></span></button>
					  <ul class="dropdown-menu">
					    <li><%= link_to "Unfriend", user_friendship_url(current_user,friend), :method=> :delete, remote: true %></li>
					  </ul>
					</div>
	    	</div>
	    </div>
	</div>
<% end %>

app/views/friendships/_pending.html.erb
<div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Friend Request Pending Approval
  <span class="caret"></span></button>
  <ul class="dropdown-menu">
    <li><%= link_to "Accept Friend", user_friendship_url(current_user,@user), :method=> :patch, remote: true %></li>
    <li><%= link_to "Reject Friend", user_friendship_url(current_user,@user), :method=> :delete, remote: true %></li>
  </ul>
</div>

app/views/friendships/_pending_friend.html.erb
<% if defined? pending_friend %>
	<div class="col-xs-4">
	    <div href="#" class="thumbnail">
	      <img src="http://placehold.it/400x200" alt="..." />
	      <div class="caption">
		      <%= link_to pending_friend.name, pending_friend %>

					<div class="dropdown">
	  			<button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Friend Request Pending Approval
	  			<span class="caret"></span></button>
	  			<ul class="dropdown-menu">
	    			<li><%= link_to "Accept Friend", user_friendship_url(current_user,pending_friend), :method=> :patch, remote: true %></li>
	    			<li><%= link_to "Reject Friend", user_friendship_url(current_user,pending_friend), :method=> :delete, remote: true %></li>
	  				</ul>
					</div>
	    	
	    	</div>
	    </div>
	</div>
<% end %>

app/views/friendships/_requested.html.erb
<div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Requested Friend
  <span class="caret"></span></button>
  <ul class="dropdown-menu">
    <li><%= link_to "Cancel Request", user_friendship_url(current_user,@user), :method=> :delete, remote: true %></li>
  </ul>
</div>

app/views/friendships/_requested_friend.html.erb
<% if defined? requested_friend %>
	<div class="col-xs-4">
	    <div href="#" class="thumbnail">
	      <img src="http://placehold.it/400x200" alt="..." />
	      <div class="caption">
		      <%= link_to requested_friend.name, requested_friend %>

					<div class="dropdown">
					  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Requested Friend
					  <span class="caret"></span></button>
					  <ul class="dropdown-menu">
					    <li><%= link_to "Cancel Request", user_friendship_url(current_user,requested_friend), :method=> :delete, remote: true %></li>
					  </ul>
					</div>
	    	</div>
	    </div>
	</div>
<% end %>

app/views/friendships/index.html.erb
<div class="container">
  <h2>Relationships</h2>
  <ul class="nav nav-pills">
    <li class="active"><a data-toggle="pill" href="#friends">Friends</a></li>
    <li><a data-toggle="pill" href="#requested">Requested Friends</a></li>
    <li><a data-toggle="pill" href="#pending">Friend Requests To Approve</a></li>

  </ul>
  
  <div class="tab-content">

    <div id="friends" class="tab-pane fade in active">
			<%= render partial: 'friendships/friend', collection: @user.friends %>
    </div>
    
    <div id="requested" class="tab-pane fade">
      <%= render partial: 'friendships/requested_friend', collection: @user.requested_friends %>

    </div>

    <div id="pending" class="tab-pane fade">
      <%= render partial: 'friendships/pending_friend', collection: @user.pending_friends %>
    </div>
  </div>
</div>

app/views/friendships/new.html.erb
<%= render 'form' %>