config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :softwares
  resources :printers
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}
  resources :users, :only => [:show]

  get 'password_resets/new'

  get 'password_resets/edit'

  root      'static_pages#home'
  get       '/help',    to: 'static_pages#help'
  get       '/about',   to: 'static_pages#about'
  get       '/contact', to: 'static_pages#contact'
  get       '/search', to: 'search#index'
	
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup


  
  resources :users do 
    resources :creations, shallow: true
    resources :friendships
  end


  resources :comments

  resources :creations, shallow: true do 
    get :download
    get :fork
  end

  resources :user_files, only: [:destroy, :create]

  resources :categories

  resources :likes, only: [:create,:destroy]
  
  resources :follows, only: [:create,:destroy]

  resources :account_activations, only: [:edit]


  resources :challenges

  resources :conversations, shallow: true do
    resources :messages
  end
  
  mount ActionCable.server, at: '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/printer.rb
class Printer < ApplicationRecord
end

app/controllers/printers_controller.rb
class PrintersController < ApplicationController
  before_action :set_printer, only: [:show, :edit, :update, :destroy]

  # GET /printers
  # GET /printers.json
  def index
    @printers = Printer.all
  end

  # GET /printers/1
  # GET /printers/1.json
  def show
  end

  # GET /printers/new
  def new
    @printer = Printer.new
  end

  # GET /printers/1/edit
  def edit
  end

  # POST /printers
  # POST /printers.json
  def create
    @printer = Printer.new(printer_params)

    respond_to do |format|
      if @printer.save
        format.html { redirect_to @printer, notice: 'Printer was successfully created.' }
        format.json { render :show, status: :created, location: @printer }
      else
        format.html { render :new }
        format.json { render json: @printer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /printers/1
  # PATCH/PUT /printers/1.json
  def update
    respond_to do |format|
      if @printer.update(printer_params)
        format.html { redirect_to @printer, notice: 'Printer was successfully updated.' }
        format.json { render :show, status: :ok, location: @printer }
      else
        format.html { render :edit }
        format.json { render json: @printer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /printers/1
  # DELETE /printers/1.json
  def destroy
    @printer.destroy
    respond_to do |format|
      format.html { redirect_to printers_url, notice: 'Printer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_printer
      @printer = Printer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def printer_params
      params.require(:printer).permit(:name)
    end
end

app/helpers/printers_helper.rb
module PrintersHelper
end

app/views/printers/_form.html.erb
<%= form_for(printer) do |f| %>
  <% if printer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(printer.errors.count, "error") %> prohibited this printer from being saved:</h2>

      <ul>
      <% printer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/printers/edit.html.erb
<h1>Editing Printer</h1>

<%= render 'form', printer: @printer %>

<%= link_to 'Show', @printer %> |
<%= link_to 'Back', printers_path %>

app/views/printers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Printers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @printers.each do |printer| %>
      <tr>
        <td><%= printer.name %></td>
        <td><%= link_to 'Show', printer %></td>
        <td><%= link_to 'Edit', edit_printer_path(printer) %></td>
        <td><%= link_to 'Destroy', printer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Printer', new_printer_path %>

app/views/printers/new.html.erb
<h1>New Printer</h1>

<%= render 'form', printer: @printer %>

<%= link_to 'Back', printers_path %>

app/views/printers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @printer.name %>
</p>

<%= link_to 'Edit', edit_printer_path(@printer) %> |
<%= link_to 'Back', printers_path %>